#!/usr/bin/env python3
"""Regenerate _tools/NODE_INDEX.md — every node ID declared so far.

Graph builders read this to make cross-subject edges against IDs that actually
exist, instead of guessing a number and leaving a dangling target.

Run:  uv run python _tools/node_index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RE_HEADING = re.compile(r"^###\s+`([A-Z]{2,5}-\d{2})`\s*·\s*(.+?)\s*$")
RE_TYPE_DEPTH = re.compile(r"\*\*Type:\*\*\s*(\w+)\s*·\s*\*\*Depth:\*\*\s*(L\d)")


def main() -> int:
    out = [
        "# NODE_INDEX — every knowledge-graph node declared so far",
        "",
        "*Generated by `_tools/node_index.py`. Do not hand-edit.*",
        "",
        "Cross-subject edges must name an ID that appears here. If the node you want to point",
        "at is not listed, the graph that would declare it has not been built yet — describe the",
        "connection in your §6 coverage gaps as prose instead of inventing an ID.",
        "",
    ]
    total = 0

    for subject_dir in sorted(ROOT.glob("[0-9][0-9]_*")):
        path = subject_dir / "00_knowledge_graph.md"
        if not path.exists():
            continue
        rows: list[str] = []
        depth = ""
        for line in path.read_text(encoding="utf-8").splitlines():
            if m := RE_HEADING.match(line):
                rows.append(f"| `{m.group(1)}` | {m.group(2)} |")
            elif m := RE_TYPE_DEPTH.search(line):
                depth = m.group(2)
        if not rows:
            continue
        total += len(rows)
        out += [f"## `{subject_dir.name}` — {len(rows)} nodes", "",
                "| ID | Node |", "|---|---|", *rows, ""]

    del depth
    out.append(f"**{total} nodes across "
               f"{sum(1 for d in ROOT.glob('[0-9][0-9]_*') if (d / '00_knowledge_graph.md').exists())} "
               f"subjects.**")
    (ROOT / "_tools" / "NODE_INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote _tools/NODE_INDEX.md — {total} nodes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
